---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - osac.openshift.io
  resources:
  - baremetalpools
  - hostleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osac.openshift.io
  resources:
  - baremetalpools/finalizers
  - hostleases/finalizers
  verbs:
  - update
- apiGroups:
  - osac.openshift.io
  resources:
  - baremetalpools/status
  - hostleases/status
  verbs:
  - get
  - patch
  - update
